spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1/first_project
    username: root
    password: worms0249

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
