constants:
  file:
    directory: /home/download

spring:
  datasource:
    url: jdbc:mariadb://192.168.0.84/first_project
    username: green1
    password: spring502
    driver-class-name: org.mariadb.jdbc.Driver