constants:
  file:
    directory: D:/hanip/images

spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://112.222.157.157:5011/first_project
    username: green1
    password: spring502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml